export const ADD_POST = "ADD_POST";
export const GET_POST = "GET_POST";
export const GET_POSTS = "GET_POSTS";
export const TIMELINE_POST_REQUEST = "TIMELINE_POST_REQUEST";
export const TIMELINE_POST_SUCCESS = "TIMELINE_POST_SUCCESS";
export const TIMELINE_POST_FAIL = "TIMELINE_POST_FAIL";
export const TIMELINE_POST_REQUEST_BY_USERID =
	"TIMELINE_POST_REQUEST_BY_USERID";
export const TIMELINE_POST_SUCCESS_BY_USERID =
	"TIMELINE_POST_SUCCESS_BY_USERID";
export const TIMELINE_POST_FAIL_BY_USERID = "TIMELINE_POST_FAIL_BY_USERID";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const POST_ERROR = "POST_ERROR";
export const ADD_LIKE = "ADD_LIKE";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const ADD_REPLY = "ADD_REPLY";
export const UPDATE_REPLY = "UPDATE_REPLY";
export const DELETE_REPLY = "DELETE_REPLY";
export const LIKE_REPLY = "LIKE_REPLY";
