export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const USER_ERROR = "USER_ERROR";
export const USER_FOLLOW = "USER_FOLLOW";
export const USER_UNFOLLOW = "USER_UNFOLLOW";

export const GET_FRIENDS_REQUEST = " GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = " GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = " GET_FRIENDS_FAIL";

export const GET_RANDOM_USER_REQUEST = " GET_RANDOM_USER_REQUEST";
export const GET_RANDOM_USER_SUCCESS = " GET_RANDOM_USER_SUCCESS";
export const GET_RANDOM_USER_FAIL = " GET_RANDOM_USER_FAIL";
